apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-k8s-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: simple-k8s-client
    spec:
      containers:
        - name: simple-k8s-client
          image: "simple-k8s-client:latest"
          env:
            - name: SERVICE_URL
              valueFrom:
                configMapKey:
                  name: simple-k8s-config
                  key: service.url