apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-k8s-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-k8s-server
  template:
    metadata:
      labels:
        app: simple-k8s-server
    spec:
      containers:
        - name: simple-k8s-server
          image: "simple-k8s-server:latest"
          imagePullPolicy: Never
#          port:
#            - containerPort: 9090
          env:
            - name: PORT
              value: "9090"

          readinessProbe:
            httpGet:
              path: /info
              port: 9090
            initialDelaySeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /info
              port: 9090
            initialDelaySeconds: 10
            timeoutSeconds: 5
